<div class="row">				
	<div class="col-md-12">
					
		<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
			<ol class="carousel-indicators">
				<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
				<li data-target="#carousel-example-generic" data-slide-to="1"></li>
				<li data-target="#carousel-example-generic" data-slide-to="2"></li>
			</ol>
					  	
			<div class="carousel-inner" role="listbox">
				<div class="item active">						     
					<img  alt="Icon Facebook" style="width:100%;height:175px" src="/images/background/head_page.jpg" data-holder-rendered="true">
					<div class="carousel-caption">
						<h3>First slide</h3>
						<p>Icon Facebook</p>
					</div>
				</div>
				<div class="item">
					<img src="/images/background/head_page2.jpg" alt="instagram" style="width:100%;height:175px" data-holder-rendered="true">
					<div class="carousel-caption">
						<h3>Second slide</h3>
						<p>Icon Instagram</p>
					</div>
				</div>
				<div class="item">
					<img src="/images/background/head_page3.jpg" alt="youtube" style="width:100%;height:175px" data-holder-rendered="true">
					<div class="carousel-caption">
						<h3>Third slide</h3>
						<p>Icon Youtube</p>
					</div>
				</div>					    
			</div>						    												
			<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
				<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			</a>
			<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
				<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			</a>										  
		</div>
	</div>				
</div>

<div class="panel"></div>

<!-- =================== Content All News ============================= -->
<div class="row">
	<!-- =================== News Feed Left ============================= -->
	<div class="col-md-8">

	
	<div class="panel">
		<div data-toggle="collapse" data-target="#collapseExample_etc" aria-expanded="false" aria-controls="collapseExample">
			<img src="/images/ryoii_etc_head.gif" alt="..." class="img-responsive img-rounded" style="width:100%">
		</div>
		<div class="collapse in" id="collapseExample_etc">
			 <div class="panel-body">
				<div class="media">
					<div class="media-left">
						<a href="#">
							<img class="media-object" src="/images/title/img_title_20160325161830.jpg" style="max-width:75px">
						</a>
					</div>
					<div class="media-body">
						<a href="#">โฮลี่ ชีส (Holy Cheese) กริลล์ชีสแซนด์วิช ชีสทะลักหนักทุกไส้ ทั้งเนื้อโคขุน หมูตุ๋น เบคอน เห็ดออรินจิ ชีสล้วนสไตล์อเมริกัน @ตลาดนัดรถไฟ รัชดา</a>
						<div class="hidden-xs">
							Grilled Cheese Sandwich” จากร้าน Holy Cheese แซนด์วิชชีสย่าง ผสมผสานความเป็นอเมริกันแนวใหม่ ทำกันสดใหม่ทุกออร์เดอร์ โดยการนำ “ชีส" ไปย่าง พร้อมวางรวมกันกับไส้ต่างๆ และนำไปอบกับขนมปัง Ciabatta สไตล์อิตาลี
						</div>
					</div>
				</div>
				<hr>
				<div class="media">
					<div class="media-left">
						<a href="#">
							<img class="media-object" src="/images/title/img_title_20160325161830.jpg" style="max-width:75px">
						</a>
					</div>
					<div class="media-body">
						<a href="#">โฮลี่ ชีส (Holy Cheese) กริลล์ชีสแซนด์วิช ชีสทะลักหนักทุกไส้ ทั้งเนื้อโคขุน หมูตุ๋น เบคอน เห็ดออรินจิ ชีสล้วนสไตล์อเมริกัน @ตลาดนัดรถไฟ รัชดา</a>
						<div class="hidden-xs">
							Grilled Cheese Sandwich” จากร้าน Holy Cheese แซนด์วิชชีสย่าง ผสมผสานความเป็นอเมริกันแนวใหม่ ทำกันสดใหม่ทุกออร์เดอร์ โดยการนำ “ชีส" ไปย่าง พร้อมวางรวมกันกับไส้ต่างๆ และนำไปอบกับขนมปัง Ciabatta สไตล์อิตาลี
						</div>
					</div>
				</div>
				<hr>
				<div class="media">
					<div class="media-left">
						<a href="#">
							<img class="media-object" src="/images/title/img_title_20160325161830.jpg" style="max-width:75px">
						</a>
					</div>
					<div class="media-body">
						<a href="#">โฮลี่ ชีส (Holy Cheese) กริลล์ชีสแซนด์วิช ชีสทะลักหนักทุกไส้ ทั้งเนื้อโคขุน หมูตุ๋น เบคอน เห็ดออรินจิ ชีสล้วนสไตล์อเมริกัน @ตลาดนัดรถไฟ รัชดา</a>
						<div class="hidden-xs">
							Grilled Cheese Sandwich” จากร้าน Holy Cheese แซนด์วิชชีสย่าง ผสมผสานความเป็นอเมริกันแนวใหม่ ทำกันสดใหม่ทุกออร์เดอร์ โดยการนำ “ชีส" ไปย่าง พร้อมวางรวมกันกับไส้ต่างๆ และนำไปอบกับขนมปัง Ciabatta สไตล์อิตาลี
						</div>
					</div>
				</div>
						   	
			</div>	
			<div class="panel-footer" style="border:none;padding:0px">
				<img src="/images/footer_etc.png"  class="img-responsive" style="width:100%;" data-toggle="collapse" data-target="#collapseExample_etc" aria-expanded="false">
			</div>		
		
		</div>
	</div>
	

	
		<?php 
			if($this->NewsFeed!=null){
				foreach ($this->NewsFeed AS $value){
				?>
					<div class="panel panel-default">
						<div class="panel-heading">
						  	<a href="/index/index?page=content&news_id=<?php echo $value->news_id;?>" class="set-tag-a"><?php echo $value->news_title?></a>
						</div>
						<div class="panel-body">
						  	<div class="row">
				
						  		<div class="col-md-12">
							  		<div style="padding:1px">
							  		<a href="/index/index?page=content&news_id=<?php echo $value->news_id;?>" style="float:left;margin:10px"><img src="/images/title/<?php echo $value->news_picture?>" class="img-thumbnail" style="width:128px;height:128px;"></a>
							  			<p><?php echo $value->news_short?></p>
									</div>
						  		</div>
						   </div>		
						   <span class="label label-info">Tags </span> 
							<a href="#" style="margin-left:5px;"><span class="label label-default">Samsung </span></a> 
							<a href="#" style="margin-left:5px;"><span class="label label-default">Phone </span></a> 		  						  			
						 </div>		  		
					</div>
				<?php 
				} 							
			}	
		?>
		
	
	</div>
	<!-- =================== End News Feed Left ============================= -->
	
	<!-- =================== Content Rigth ============================= -->
	<div class="col-md-4">
		<div class="panel panel-default">			  		
			<div class="panel-body" style="text-align:center;">
			    <div style="min-height:300px">
			    	<label>Advertise</label>
						
						<div class="fb-page" data-href="https://www.facebook.com/techmoblog" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/techmoblog"><a href="https://www.facebook.com/techmoblog">TechmoBlog : Tech your life</a></blockquote></div></div>			    				   													    	
			    </div>			    					
			 </div>
		</div>
	</div>
	<!-- ===================End Content Rigth ============================= -->
</div>
<!-- ===================End Content All News ============================= -->