<script>
	function readURLImgEdit(img){
		
		if(img.files&&img.files[0]){
			var reader = new FileReader();
	        reader.onload = function (e) {
	            $('#img_preview_upload_edit').attr('src', e.target.result);
	        };
	        reader.readAsDataURL(img.files[0]);	        	
		}else{
			$('#img_preview_upload_edit').attr('src',"/images/noimage.jpg");
		}
		// ----------- Set Value Null For Check Case Edit Upload Image ------------------- 
		$("#input_name_imageTitle_edit").val("");
	}

	function ManagementImages() {
	    var myWindow = window.open("/management-images/index", "", "width=1200, height=600");
	}
  $(document).ready(function(){
	  //======= Create CKeditor ========== 
	  CKEDITOR.replace('editor_news_edit',{
		  height:500
		});

	  //========== Event Button Upload Image On Change ===========
	  $("#inputImgTitle_edit").change(function() {
		  readURLImgEdit(this);
		});

		//========= Event Button Detail Images On Click ===========
		$("#btn_detial_images_edit").on('click',function(){
			ManagementImages();
		});
	});
  
</script>
<div class="panel panel-default" >					
	<div class="panel-heading" style="text-aling:center">
		<label>แก้ไขข่าว</label>
	</div>
	<div class="panel-body">
	<form role="form" action="/index/edit-news" method="POST" id="form_edit_news" enctype="multipart/form-data">			  			
		<div class="form-group">
			<label>หัวข้อข่าว</label>
			<input type="text" name="title_news_edit" id="title_news_edit" class="form-control input-sm" value=" <?php echo $this->dataNews->news_title;?>" placeholder="" required>							
		</div>
		<div class="form-group">
			<label>ข่าวย่อ</label>							
            <textarea class="form-control" name="input_news_short_edit" id="input_news_short_edit" rows="5" required><?php echo $this->dataNews->news_short;?></textarea>	
            							
		</div>
		<div class="form-group">
			<label for="inputImgTitle_edit">ภาพหัวข้อข่าว</label>
			<input type="file" id="inputImgTitle_edit" name="inputImgTitle_edit" accept="image/*" value="<?php echo $this->dataNews->news_picture;?>">
			<input type="hidden" id="input_name_imageTitle_edit" name="input_name_imageTitle_edit" value="<?php echo $this->dataNews->news_picture;?>" required />
			<p class="help-block">Example</p>
			<span><img id="img_preview_upload_edit" src="/images/<?php echo $this->dataNews->news_picture?'title/'.$this->dataNews->news_picture:'noimage.jpg';?>" width="128" height="128" alt="..." class="img-thumbnail"></span>							    
			<input style="max-width:150px;margin-top:10px" type="button" id="btn_detial_images_edit" value="ข้อมูลรูปภาพ" class="btn btn-info btn-block">
		</div>
		<div class="form-group">
			<label>เพิ่มเนื้อหา</label>
			<textarea name="editor_news_edit" id="editor_news_edit" rows="15" cols="80">
               <?php echo $this->dataNews->news_content;?>
            </textarea>															
		</div>
		<input type="hidden" id="input_news_id_edit" name="input_news_id_edit" value="<?php echo $this->dataNews->news_id?>"/> 
		<button type="submit" class="btn btn-success">บันทึกข้อมูล</button>			
		<!-- button type="cancel" class="btn btn-danger">เก็บลงถังขยะ</button -->				
	</form>
	</div>
</div>