<!DOCTYPE html>
<html>
<head>
	<title>System Admin</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Set Icon Favicon Teb Website --> 
    <link rel="shortcut icon" type="image/x-icon" href="/images/icon/home.png" />
    <!-- Jquery UI CSS -->
    <link href="/assets/jquery-ui/jquery-ui.css" rel="stylesheet">
     <!-- Bootstrap -->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">

    <script src="/assets/js/jquery.js"></script>
    <script src="/assets/jquery-ui/jquery-ui.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
</head>
<body>
	<div class="container">	<?php echo $this->layout()->content; ?></div>

	 <footer class="footer">
      <div class="container">
        <p class="text-muted" style="text-align:center">WebAdministrator @TMC</p>
      </div>
    </footer>
   
</body>	
</html>
